### PR TITLE
Indentation

### PR DESCRIPTION
**Pull request by Swizec**
This resolves feature requests #98 and #43 to a certain extent.

Tab increased the indentation of the current line by four spaces, no matter where in the line it is pressed.

Shift+Tab decreases indentation.

Going to a new line maintains indentation from the previous line as long as it was made with spaces.

TODO: indenting a block of text
should eventually be refactored with a central syntax logic
eventually needs preferences

PS: since this is my first time coding objC please have a look through my commits to see if I did anything horribly stupid (and let me know)

### CODE REVIEW

**Comment by Swizec** [comment]
Actually I just realised there is likely a nasty bug in the way I maintain indentation when going to a new line.

Please refrain from merging until I figure this one out, shouldn't take more than a day or so :)

**Comment by rsms** [comment]
Nice. Just a few things related to style and performance:
- Please follow the over-all style of Kod source and write `} else {` instead of `}else{` please.
- Avoid unnecessary objective-c calls in functions which are called often and block the UI. For instance, instead of calling this `self.textStorage.delegate` several times in the same scope, put the result on the stack and use that (i.e. `KDocument *doc = self.textStorage.delegate`)
- `rangeOfLineIndentationAtLineNumber` is very inefficient (NSString's `characterAtIndex:` in particular). Better to use `rangeOfCharacterFromSet:` with `[NSCharacterSet whitespaceCharacterSet]`
- `[[self selectedRanges] objectAtIndex:0]` involves creating a temporary NSArray just to throw it away afterwards. Prefer to use `selectedRange` instead.
- `locationOfLineAtLineNumber:` seems a bit unnecessary to me when you can use the equally "explanative" but slightly faster `rangeOfLineAtLineNumber:].location`
- In `indentLine:`, don't call super's implementation of `setSelectedRange:` and `insertText:` -- you should call self's implementation (`super` is a special keyword and not a variable in objective-c, btw).

I'm very sorry if I'm a bastard, but I want to keep Kod fast and its code consistent.

Also, I just pushed a rather extensive update to master -- you might want to pull & merge that before fixing the quirks.

Thanks!

**Comment by Swizec** [comment]
Thanks for the helpful pointers, as stated, being a complete objC novice I have no idea about a lot of these things :)

**Comment by Swizec** [comment]
The new commits address some of the performance issues you mentioned and fix all known bugs.

Some of your suggestions I couldn't quite implement. Namely the 
- locationOfLineAtLineNumber had to stay because otherwise I kept getting EXC_BAD_ACCESS errors
- the rangeOfCharacterFromSet didn't really seem more efficient since it can only give the range of a single character at a time, so if I wanted to find the range of a chunk of characters I would have to keep substringing the whole line and that seems wasteful. Maybe I'm thinking about it wrong?

Cheers
~Swizec

**Comment by Swizec** [comment]
Just noticed another ticket was opened about this #70

**Comment by rsms** [comment]
Many thanks! Landed in master.

**Pull request merged**
