### PR TITLE
Cloaking the background

### PR DESCRIPTION
**Pull request by epatel**
Hi Rasmus!
Couldn't resist to fork this and checkout the project! So, as a little _thing_ I added a backdrop/cloak window that covers the (main) display hiding the desktop, icons and windows making a calmer editing experience. 
Grab it if you like it.
Cheers!
Edward

### CODE REVIEW

**Comment by epatel** [comment]
oh yes. I should add that the _feature_ is available from the View menu.

**Comment by rsms** [comment]
Quite a nice feature. Would you mind moving the `UnclutterView` into its own file and name it something that's a little more self-explanatory? For instance `KWindowBackgroundCoverView` (that relates to what the feature is called/named in the interface). Also, would you make the background window hide when Kod is deactivated? I think it's as easy as sending `setHidesOnDeactivate:YES` to the NSWindow.

And then there's the code "rumsrenhet":

Please follow the Google Objective-C code style guidelines (link and info in the wiki), thus:

```
- (IBAction)coverBackground:(id)sender
{
```

Become:

```
- (IBAction)coverBackground:(id)sender {
```

And `-[KAppDelegate coverBackground:]` is placed under the "NSServices" group of the source file. It should probably move to the "Actions" group.

**Comment by epatel** [comment]
Sure can do. I get to discover the finer details of the project. 

About the `setHidesOnDeactivate:YES`. I tried that first but thought it made my display flicker a little to much when going back and forth between Kod and the Terminal. With `setHidesOnDeactivate:NO` (default) a Terminal window can stay up front together with the Kod windows. But, I have enabled `setHidesOnDeactivate:YES` so you can try it.

**Comment by epatel** [comment]
I'll have a look to save the state in the preferences too.

**Comment by rsms** [comment]
Regarding `setHidesOnDeactivate:YES`: Well, leave it as NO then. I guess this is a very "narrow" feature. I mean, OS X already provides a convention for "clean up all this mess!" (Cmd+Alt+H), so I imagine not many people will use this. But as it doesn't impact the default user interface nor performance or code clutter, I guess an extra menu item won't hurt :)

Look in kconf.h for the interface to the prefs. For instance, reading the value:

```
BOOL isActive = kconf_bool(@"window/backgroundCover/enabled", NO);
```

And setting it:

```
kconf_set_bool(@"window/backgroundCover/enabled", isActive);
```

Note: Setting and getting is very cheap, so no need to defer setting.

**Comment by epatel** [comment]
Moved the stuff a little and made a little renaming. I noticed the little "_" last in your members. Also added it to the preferences as you described above.

**Comment by epatel** [comment]
I saw some mentioning about a 80 chars guide line so I figured I'll try to add that. I added a `drawRect:` method of the `KTextView` and a small calculation of the necessary width in `refreshStyle`

**Comment by rsms** [comment]
Nice work. Landed in rsms/kod@9e6efacc0b7d31c7b3cfc51160f236244c3e4db6

**Pull request merged**
