### PR TITLE
More style-able elements

### PR DESCRIPTION
**Pull request by agos**
Removed hardcoded styling for document background, default text color, caret (insertion point), and selected text. Added relevant CSS information where needed.

Ultimate styling in action

### CODE REVIEW

**Comment by rsms** [comment]
Nice. Would you mind adding support for when the style is reloaded too? Have a look at https://github.com/rsms/kod/blob/dc86414c0ab/src/KMetaRulerView.mm#L65 for some inspiration (you can basically copy-paste from that one). And don't forget to unregister in dealloc.

**Comment by agos** [comment]
Sure, I'm working on this right now. A question for testing purposes: which is the easiest way to trigger that notification?

**Comment by rsms** [comment]
When Kod is running, open Kod.app/Contents/Resources/style/default.css and modify it. Kod will know it's the same style it's using and issue a reload of it.

**Comment by agos** [comment]
I got it to correctly change all the colors, but can't get it to change the font. Should I setFont on KTextView or on KTextStorage? Or both? Is asking setViewsNeedDisplay enough to redraw it afterwards? I think it should be. Maybe I'm not really using the a different NSFont, but I suck at GDB and can't find a way to inspect it.

**Comment by agos** [comment]
Finally got it working! I was looking everywhere, minus the right place.

**Pull request merged**
