### PR TITLE
Line numbers bug

### PR DESCRIPTION
**Pull request by Swizec**
This solves ticket #19

The problem seemed to have been removing lines while at the same time adding new ones. I solved this by recursing the `_updateLinesToRangesInfoForTextStorage` function. This way it first recalibrates for the removed text and then for the added text.

Simply removing some text doesn't trigger the recursion.

Also, sorry for the 12 commit pull request, it should be just a 2 commit one since I used a topic branch, github is being strange.

### CODE REVIEW

**Comment by rsms** [comment]
Line 3 of pull.sh seems to be invalid/broken? Also, if you change it to use upstream by default (a good idea!) then maybe adding a line or two about how to make it work in the README (i.e. git remote add upstream ...)?

While at it, would you please mind fixing some sanitary stuff:
- **NO** tab characters in the source code. Please use two spaces as dictated by http://google-styleguide.googlecode.com/svn/trunk/objcguide.xml?showone=Spaces_vs._Tabs#Spaces_vs._Tabs (which is linked to from https://github.com/rsms/kod/wiki/Code-style-guide)
- Double space (or tab) in `}  else if` should be single space
- Method call at line 1433 of src/KDocument.mm should be correctly wrapped (see the code guideline if unsure of how)

Thanks

**Comment by rsms** [comment]
Can I close this now? (since I pulled in the other one which seemed to contain the same stuff)

**Comment by rsms** [comment]
BTW, why are you not hanging out in [irc://irc.freenode.net/#kod](irc://irc.freenode.net/#kod)?

**Comment by rsms** [comment]
Seems like it didn't quite get solved:

image

**Comment by Swizec** [comment]
Yeah sorry I had to get some sleep, had been up for two days :)

Anyway, could you just tell me what you did to get that screenshot? I'll try fixing it more.

**Pull request closed without merging**
