### PR TITLE
M+ 1m font with Cyrillic support

### PR DESCRIPTION
**Pull request by kossnocorp**
Ticket:

http://hunch.lighthouseapp.com/projects/66522-kod/tickets/178-m-1m-font-with-cyrillic-support#ticket-178-2

### CODE REVIEW

**Comment by rsms** [comment]
Please also sign the CLA: http://kodapp.com/cla.html

**Comment by kossnocorp** [comment]
I did it before send pull request.

**Comment by rsms** [comment]
Weird... I can't find you in the data spreadsheet: http://d.pr/SpaZ (I'm assuming your name is "Sasha Koss"  as stated on https://github.com/kossnocorp)

**Comment by rsms** [comment]
I found an entry by a "Aleksandr Kostyutchenko" pointing to your github URL. Is that you? For legal reasons, this need to be your real name and so should the entry in AUTHORS.md be. (Sorry for any inconvenience)

**Comment by kossnocorp** [comment]
Aleksandr Kostyutchenko is my full real name. Aleksandr is same name as Sasha, but Koss is my pseudonym. Should I do something?

**Comment by rsms** [comment]
It's ok. I'll update the AUTHORS.md to reflect the name used to sign the CLA.

**Pull request merged**
