### PR TITLE
Update gazelle-build.sh to support Xcode 4

### PR DESCRIPTION
**Pull request by plambert**
Updated gazelle-build.sh to support Xcode 4 build locations

### CODE REVIEW

**Comment by aslilac** [comment]
Please Rasmus, do it. I ditched Xcode 3 and now I can't build with my updates. :(

**Comment by rsms** [comment]
Thanks. I haven't had the opportunity to test this myself though, but it works for Xcode 3. Xcode 4 users; please let me know if you're still experiencing issues.

**Comment by agos** [comment]
I found some more XCode4 issues, but I think they're all pretty easy to fix. Will investigate and make pull request if I can fix that.

**Comment by aslilac** [comment]
Build still fails for me. :(

**Comment by agos** [comment]
@tylermwashburn: please refer to ticket #52, I managed to build and posted the two things I needed to do there. If it still doesn't work for you, please post any error there, and I'll look into it.

**Pull request merged**
